# Generated by Django 3.1.6 on 2021-02-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='especificacoes',
            field=models.TextField(max_length=2000),
        ),
    ]
